Update encoding in movielens_recommendations_transformers.py
At present the example tutorial raising the UnicodeDecodeError at the code movies=pd.read_csv()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3114: invalid continuation byte

Hence adding the encoding='latin-1' to the movies=pd.read_csv(...,encoding='latin-1') will get rid of this error.

Hence I proposed this code change for review and approval.