Update gnn_citations.py (#1761)
* Update gnn_citations.py

Fixing a simple issue

Traceback (most recent call last):
  File "/Users/xxxxxx/Desktop/keras-io/examples/graph/gnn_citations.py", line 251, in <module>
    x_train = train_data[feature_names].to_numpy()
              ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/frame.py", line 3857, in __getitem__
    check_dict_or_set_indexers(key)
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/core/indexing.py", line 2687, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.

Convert to list

* Update gnn_citations.ipynb

Also update set to list in ipynb file

* Update gnn_citations.md

Also update .md file